# Use uma imagem base para Node.js
FROM node:18

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie apenas os arquivos de dependências primeiro
COPY package*.json ./

# Instale as dependências do projeto
RUN npm install

# Copie o restante dos arquivos do backend para o contêiner
COPY . .

# Exponha a porta que o backend usa
EXPOSE 3000

# Comando para iniciar o servidor
CMD ["npm", "run", "dev"]
